### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by vvzar** [HellionCommunity/HellionExtendedServer#19]
you have memory leak, gentlemen.
server windows 2008 r2
80 cpu
96gb ram
original server process - 128-256 RAM
extended server process - 8gb (all free ram)

**Comment by generalwrex** [comment]
Is there anymore information on this? We're not doing anything in HES that should really change the memory usage. ;)

**Comment by vvzar** [comment]
Sorry, it happened only once.  Will look into it. Is any debug options or something to enable?

**Comment by vvzar** [comment]
![image](https://cloud.githubusercontent.com/assets/5399200/23945643/541f990a-0988-11e7-88c7-13172e50a31f.png)

![log_leak_1](https://cloud.githubusercontent.com/assets/5399200/23946028/d6b52104-0989-11e7-937c-dfc181f28113.png)
![log_leak_2](https://cloud.githubusercontent.com/assets/5399200/23946025/d6b25ece-0989-11e7-9d06-dce5fca7635a.png)
![log_leak_3](https://cloud.githubusercontent.com/assets/5399200/23946026/d6b3d362-0989-11e7-86dc-5757b51c2cc3.png)
![log_leak_4](https://cloud.githubusercontent.com/assets/5399200/23946027/d6b41a52-0989-11e7-8f01-5da5a8981129.png)

Sorry only this way I can post all information I have.

**Comment by generalwrex** [comment]
Anything that says [ERROR] and in grey is Hellion Dedicated, Things in white are from HES, for the memory leak, there is seriously nothing within HES to cause it. We'll look more into it however.

**Comment by generalwrex** [comment]
How big are your saves?  Have you tried moving them to another folder to see if it still did it? Considering pre-alpha with a pre-alpha extender ;)

**Comment by generalwrex** [comment]
```
Using private bytes performance counters to detect memory leak
In order to get the right amount of memory consumed by the application we need to track the private bytes consumed by the application. Private bytes are those memory areas which are not shared by other applications. In order to detect private bytes consumed by an application we need to use performance counters.

Below are the steps we need to follow to track private bytes in an application using performance counters:

Start your application which has memory leaks and keep it running.
Click Start -> go to Run, and type ‘perfmon’.
Delete all the current performance counters by selecting the counter and deleting them by hitting the Delete button.
Right click, select ‘Add counters’, select ‘Process’ from the performance object.
From the counter list select ‘Private bytes’.
From the instance list select the application which you want to test memory leak for.
If your application shows a steady increase in private bytes value that means we have a memory leak issue here. You can see in the below figure how the private bytes value is increasing steadily thus confirming that the application has a memory leak.
```

Source: https://www.codeproject.com/Articles/42721/Best-Practices-No-Detecting-NET-application-memo

**Comment by vvzar** [comment]
Before I`ll do what you recommend, I post my thoughts.
It happened after many spawns of existent players since last launch of HES.
And never happens when amount of spawns relatively low.
I hope this information will help too.

**Comment by generalwrex** [comment]
Closing this issue as it was for a old outdated version! Open it back up if the problem still exists!
