### ISSUE TITLE
Plugin Implementation and Command Implementation

### ISSUE THREAD

**Issue by yungtechboy1** [HellionCommunity/HellionExtendedServer#20]
Mind if I push and help out with implementing Plugin support and Commands?

**Comment by generalwrex** [comment]
Sure thing ;) Just fork it out and do whatever!  the plugin interface and base classes are in the common dll, the manager is in the exe project, and the dev branch has the gui enabled if you wanted to program in the plugin ui tab. However we need to convert some of the classes from ZG's stuff into the API for the plugins to use, and HES itself to use.

**Comment by yungtechboy1** [comment]
Here is my branch! So far I have commands working and I will start working on Plugin Loading
https://github.com/yungtechboy1/HellionExtendedServer/tree/Plugins

**Comment by yungtechboy1** [comment]
Just got done with all the Basic Plugin Stuff and Command Manager

**Comment by generalwrex** [comment]
I should mention this, there's a new Folder structure for HES

in the server directory it's now just

HellionExtendedServer.exe
HellionExtendedServer.exe.config
Hes/bin/(hes references)
Hes/logs/(the logs created from NLog)
Hes/updates(for the update manager)
Hes/plugins(maybe here for plugins?)

Currently its local changes, but I changed it to use a folder incase we have to use any more libraries and what not

**Comment by yungtechboy1** [comment]
Ok i can change it over tomorrow

**Comment by generalwrex** [comment]
I'll push my changes to dev soon, I'll just keep the update section local till i'm done and push it on its own branch,  V0.0.1.8 is going to make a lot of people happy.  Thank you so much for contributing!!!! You don't know how happy it makes me ;)

**Comment by yungtechboy1** [comment]
No Problem man! 😄

**Comment by yungtechboy1** [comment]
Also do you have a Discord? Or Twitter?

**Comment by yungtechboy1** [comment]
@generalwrex ?

**Comment by generalwrex** [comment]
Opps, I thought I said to add me on steam somewhere =P  'webwrex'

**Comment by generalwrex** [comment]
https://discord.gg/6tdjXFb

**Comment by generalwrex** [comment]
As Yung is a dev now, closing this issue =P
