### ISSUE TITLE
Crash when closing server

### ISSUE THREAD

**Issue by Sim-ian** [HellionCommunity/HellionExtendedServer#31]
Been getting a crash when using CTRL+C to shut down server. It's not saving either possibly as the crash is before the save initiated but i can manually /save and that works OK.

![20170309095821_1](https://cloud.githubusercontent.com/assets/26321894/23788147/301059c4-056d-11e7-8604-734472c1d58d.jpg)

**Comment by yungtechboy1** [comment]
@Sim-ian Yea i noticed that Server does not like Control + C. It prefers /stop. Will look into

**Comment by generalwrex** [comment]
Whoops, didn't mean to close it! just reference!

**Comment by generalwrex** [comment]
This has been fixed in the recent updates to HES. Ctrl+C now stops a running server, saves, and closes without erroring.
