### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by 2kohm** [HellionCommunity/HellionExtendedServer#32]
0.0.1.8-DEV eats up to 5GB and don´t stop there.
Windows server 2012 (32GB RAM)
HELLION_Dedicated.exe eats 200-400MB Max

**Comment by yungtechboy1** [comment]
Will look into

**Comment by yungtechboy1** [comment]
@2kohm How many players are normally on your server?

**Comment by 2kohm** [comment]
5-10 players

**Comment by generalwrex** [comment]
https://github.com/generalwrex/HellionExtendedServer/issues/19#issuecomment-286712395

Could you try this as well the next time it happens?

**Comment by generalwrex** [comment]
Closing this issue as it was for a old outdated version! Open it back up if the problem still exists!
