### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by GLotsapot** [HellionCommunity/HellionExtendedServer#82]
Checked out the repo and tried to build the solution. 

- HellionExtendedServer.common builds fine into it's own 'bin' folder. 
- HellionExtendedServer fails to build as it cannot find HellionExtendedServer.Common.dll in the HellionExtendedServer bin folder.

Manually copying the common dll file to the HellionExtendedServer\bin\debug folder allows the project to build

**Comment by GLotsapot** [comment]
Resolved by going to Solution Properties -> Configuration Properties, and setting the HellionExtendedServer.common to Build

**Comment by GLotsapot** [comment]
Looks like you could even get rid of the HellionExtendedServer project Post Build events as well after this change is made

**Comment by generalwrex** [comment]
Sorry I was 3 years late, all good now ;)
